package com.aarh.borutoapp.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_SMALL_PADDING = 2.dp
val MIN_PADDING = 4.dp
val SPACY_BETWEEN = 6.dp
val SMALL_PADDING = 8.dp
val MEDIUM_PADDING = 16.dp
val MIN_LARGE_PADDING = 24.dp
val LARGE_PADDING = 32.dp
val EXTRA_LARGE_PADDING = 40.dp

val INDICATOR_SIZE = 12.dp

val HERO_ITEM_HEIGHT = 400.dp
val NAME_PLACEHOLDER_HEIGHT = 32.dp
val ABOUT_PLACEHOLDER_HEIGHT = 16.dp
val RATING_PLACEHOLDER_HEIGHT = 24.dp
val NETWORK_ERROR_ICON_HEIGHT = 120.dp

val ICON_SIZE = 32.dp
val MIN_SHEET_HEIGHT = 150.dp
val EXPANDED_RADIUS_LEVEL = 0.dp

